# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-26 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_field', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_field', models.CharField(max_length=255)),
                ('title_field', models.CharField(max_length=255)),
                ('comment_field', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('pub_date', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Country')),
            ],
        ),
    ]
