# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-26 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspage',
            old_name='comment_field',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='newspage',
            old_name='news_field',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='title_field',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='url',
        ),
        migrations.AlterField(
            model_name='newspage',
            name='pub_date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
