# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-28 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_auto_20180626_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='title_field',
            new_name='title',
        ),
    ]
