# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-24 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_auto_20180724_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='slug',
        ),
        migrations.AlterField(
            model_name='newspage',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, unique=True),
        ),
    ]
