# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-27 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_auto_20180725_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='image',
            field=models.ImageField(default='image field', upload_to=''),
        ),
    ]
