# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-02 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_auto_20180727_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_created=True)),
                ('text', models.CharField(max_length=99999)),
            ],
        ),
        migrations.AlterField(
            model_name='newspage',
            name='image',
            field=models.ImageField(default='image field', upload_to=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='news_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.NewsPage'),
        ),
    ]
