# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-02 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0013_auto_20180802_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment_text',
        ),
    ]
