# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-07 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0016_auto_20180806_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, height_field=90, upload_to='profile_images', width_field=60),
        ),
    ]
