# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0018_auto_20180809_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_profile',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='news_page',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='football.NewsPage'),
        ),
    ]
