# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-11 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0019_auto_20180810_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
