# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-13 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0020_auto_20180811_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=40),
        ),
    ]
