# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-13 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0021_userprofile_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='slug',
            new_name='slug_n',
        ),
    ]
