# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-13 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0022_auto_20180813_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='slug_n',
            new_name='slug',
        ),
    ]
