# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-13 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0023_auto_20180813_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
