# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-15 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0024_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='NestedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nested_comment_text', models.CharField(max_length=999)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='football.Comment')),
            ],
        ),
    ]
