# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-15 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0025_nestedcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='football.Comment'),
        ),
    ]
