# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-31 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0026_comment_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nestedcomment',
            name='comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, to='football.Comment'),
        ),
        migrations.DeleteModel(
            name='NestedComment',
        ),
    ]
