# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0031_auto_20180924_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
